In [1]:
import numpy as np
import pandas as pd

In [2]:
matches = pd.read_csv("matches-IPL.csv")

In [3]:
deliveries = pd.read_csv("deliveries.csv")

In [4]:
deliveries["batsman"].unique()

array(['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuvraj Singh',
       'DJ Hooda', 'BCJ Cutting', 'CH Gayle', 'Mandeep Singh', 'TM Head',
       'KM Jadhav', 'SR Watson', 'Sachin Baby', 'STR Binny', 'S Aravind',
       'YS Chahal', 'TS Mills', 'A Choudhary', 'PA Patel', 'JC Buttler',
       'RG Sharma', 'N Rana', 'AT Rayudu', 'KH Pandya', 'KA Pollard',
       'HH Pandya', 'TG Southee', 'AM Rahane', 'MA Agarwal', 'SPD Smith',
       'BA Stokes', 'MS Dhoni', 'JJ Roy', 'BB McCullum', 'SK Raina',
       'AJ Finch', 'KD Karthik', 'G Gambhir', 'CA Lynn', 'MK Tiwary',
       'DT Christian', 'HM Amla', 'M Vohra', 'WP Saha', 'AR Patel',
       'GJ Maxwell', 'DA Miller', 'Vishnu Vinod', 'Iqbal Abdulla',
       'P Negi', 'AP Tare', 'SW Billings', 'KK Nair', 'SV Samson',
       'RR Pant', 'CH Morris', 'CR Brathwaite', 'PJ Cummins', 'A Mishra',
       'S Nadeem', 'Z Khan', 'DR Smith', 'DS Kulkarni', 'P Kumar',
       'Basil Thampi', 'RV Uthappa', 'MK Pandey', 'YK Pathan', 'SA Yadav',
       'CR Woakes', 'SP Narine', 'Harbhajan Singh', 'AB de Villiers',
       'CJ Anderson', 'F du Plessis', 'RA Tripathi', 'R Bhatia',
       'DL Chahar', 'A Zampa', 'AB Dinda', 'Imran Tahir', 'NV Ojha',
       'V Shankar', 'Rashid Khan', 'B Kumar', 'MP Stoinis', 'MM Sharma',
       'VR Aaron', 'V Kohli', 'MJ McClenaghan', 'Ankit Sharma',
       'SN Thakur', 'RD Chahar', 'LH Ferguson', 'C de Grandhomme',
       'Bipul Sharma', 'SS Iyer', 'EJG Morgan', 'KC Cariappa',
       'Sandeep Sharma', 'Ishan Kishan', 'JD Unadkat', 'AF Milne',
       'S Badree', 'AD Mathews', 'Mohammed Shami', 'Mohammad Nabi',
       'I Sharma', 'RA Jadeja', 'AJ Tye', 'KS Williamson', 'SE Marsh',
       'Shakib Al Hasan', 'JP Faulkner', 'MG Johnson', 'K Rabada',
       'AD Nath', 'NM Coulter-Nile', 'Kuldeep Yadav', 'UT Yadav',
       'Washington Sundar', 'KV Sharma', 'DM Bravo', 'AR Bawne',
       'SP Jackson', 'MJ Guptill', 'Anureet Singh', 'IK Pathan',
       'Ankit Soni', 'JJ Bumrah', 'SL Malinga', 'PJ Sangwan', 'S Kaul',
       'LMP Simmons', 'MN Samuels', 'Swapnil Singh', 'R Tewatia',
       'MM Patel', 'SS Tiwary', 'TA Boult', 'CJ Jordan', 'IR Jaggi',
       'PP Chawla', 'AS Rajpoot', 'SC Ganguly', 'RT Ponting', 'DJ Hussey',
       'Mohammad Hafeez', 'R Dravid', 'W Jaffer', 'JH Kallis', 'CL White',
       'MV Boucher', 'B Akhil', 'AA Noffke', 'SB Joshi', 'ML Hayden',
       'MEK Hussey', 'JDP Oram', 'S Badrinath', 'K Goel', 'JR Hopes',
       'KC Sangakkara', 'SM Katich', 'T Kohli', 'M Kaif', 'DS Lehmann',
       'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'V Sehwag',
       'L Ronchi', 'ST Jayasuriya', 'DJ Thornely', 'PR Shah', 'AM Nayar',
       'SM Pollock', 'S Chanderpaul', 'LRPL Taylor', 'AC Gilchrist',
       'Y Venugopal Rao', 'VVS Laxman', 'A Symonds', 'SB Styris',
       'AS Yadav', 'SB Bangar', 'WPUJC Vaas', 'RP Singh', 'LR Shukla',
       'DPMD Jayawardene', 'S Sohal', 'B Lee', 'WA Mota', 'Kamran Akmal',
       'Shahid Afridi', 'DJ Bravo', 'MA Khote', 'A Nehra', 'GC Smith',
       'Pankaj Singh', 'RR Sarwan', 'S Sreesanth', 'VRV Singh',
       'R Vinay Kumar', 'AB Agarkar', 'M Kartik', 'Shoaib Malik',
       'MF Maharoof', 'VY Mahesh', 'TM Srivastava', 'B Chipli',
       'DW Steyn', 'DB Das', 'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna',
       'SA Asnodkar', 'Sohail Tanvir', 'Salman Butt', 'BJ Hodge',
       'Umar Gul', 'SP Fleming', 'S Vidyut', 'JA Morkel', 'LPC Silva',
       'DB Ravi Teja', 'Misbah-ul-Haq', 'YV Takawale', 'RR Raje',
       'Mohammad Asif', 'GD McGrath', 'Joginder Sharma', 'MS Gony',
       'M Muralitharan', 'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha',
       'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar', 'PP Ojha',
       'SP Goswami', 'SR Tendulkar', 'U Kaul', 'TM Dilshan',
       'AD Mascarenhas', 'Niraj Patel', 'LA Pomersbach', 'Younis Khan',
       'PM Sarvesh Kumar', 'DP Vijaykumar', 'Shoaib Akhtar',
       'Abdur Razzak', 'H Das', 'SD Chitnis', 'CRD Fernando',
       'VS Yeligati', 'L Balaji', 'A Mukund', 'RR Powar', 'JP Duminy',
       'A Flintoff', 'T Thushara', 'JD Ryder', 'KP Pietersen',
       'T Henderson', 'Kamran Khan', 'RS Bopara', 'R Bishnoi',
       'FH Edwards', 'PC Valthaty', 'RJ Quiney', 'AS Raut',
       'Yashpal Singh', 'M Manhas', 'AA Bilakhia', 'AN Ghosh',
       'BAW Mendis', 'DL Vettori', 'MN van Wyk', 'RE van der Merwe',
       'TL Suman', 'Shoaib Ahmed', 'GR Napier', 'KP Appanna',
       'LA Carseldine', 'SM Harwood', 'M Vijay', 'SB Jakati', 'RJ Harris',
       'D du Preez', 'M Morkel', 'J Botha', 'C Nanda', 'Mashrafe Mortaza',
       'A Singh', 'GJ Bailey', 'AB McDonald', 'Y Nagar', 'SS Shaikh',
       'R Ashwin', 'Mohammad Ashraful', 'CA Pujara', 'OA Shah',
       'Anirudh Singh', 'Jaskaran Singh', 'R Sathish', 'R McLaren',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'YA Abdulla',
       'JM Kemp', 'S Tyagi', 'RS Gavaskar', 'SE Bond', 'S Ladda',
       'DP Nannes', 'MJ Lumb', 'DR Martyn', 'S Narwal', 'AB Barath',
       'FY Fazal', 'AC Voges', 'MD Mishra', 'J Theron', 'SJ Srivastava',
       'R Sharma', 'SW Tait', 'KB Arun Karthik', 'KAJ Roach',
       'PD Collingwood', 'CK Langeveldt', 'VS Malik', 'A Mithun',
       'AP Dole', 'AN Ahmed', 'RS Sodhi', 'DE Bollinger', 'S Sriram',
       'B Sumanth', 'C Madan', 'AG Paunikar', 'MR Marsh', 'Harmeet Singh',
       'RV Gomez', 'AUK Pathan', 'UBT Chand', 'DJ Jacobs', 'Sunny Singh',
       'NJ Rimmington', 'AL Menaria', 'WD Parnell', 'JJ van der Wath',
       'R Ninan', 'MS Wade', 'TD Paine', 'SB Wagh', 'AC Thomas',
       'JEC Franklin', 'DH Yagnik', 'S Randiv', 'BJ Haddin',
       'NLTC Perera', 'NL McCullum', 'JE Taylor', 'J Syed Mohammad',
       'RN ten Doeschate', 'TR Birt', 'AG Murtaza', 'Harpreet Singh',
       'M Klinger', 'AC Blizzard', 'I Malhotra', 'L Ablish', 'CA Ingram',
       'P Parameswaran', 'CJ Ferguson', 'AA Chavan', 'ND Doshi',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'RE Levi', 'KK Cooper',
       'HV Patel', 'DAJ Bracewell', 'DJ Harris', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'Azhar Mahmood', 'RJ Peterson',
       'KMDN Kulasekara', 'A Ashish Reddy', 'V Pratap Singh',
       'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh', 'AP Majumdar',
       'PA Reddy', 'K Upadhyay', 'P Awana', 'AD Russell', 'A Chandila',
       'Sunny Gupta', 'MC Juneja', 'GH Vihari', 'MDKJ Perera', 'R Shukla',
       'B Laughlin', 'BMAJ Mendis', 'R Rampaul', 'SMSM Senanayake',
       'BJ Rohrer', 'KL Rahul', 'Q de Kock', 'R Dhawan', 'LJ Wright',
       'IC Pandey', 'CM Gautam', 'X Thalaivan Sargunam', 'DJG Sammy',
       'KW Richardson', 'UA Birla', 'Parvez Rasool', 'PV Tambe',
       'NJ Maddinson', 'JDS Neesham', 'MA Starc', 'BR Dunk', 'RR Rossouw',
       'Shivam Sharma', 'VH Zol', 'BE Hendricks', 'S Gopal', 'M de Lange',
       'JO Holder', 'Karanveer Singh', 'SA Abbott', 'J Suchith',
       'RG More', 'D Wiese', 'SN Khan', 'DJ Muthuswami', 'C Munro',
       'P Sahu', 'KJ Abbott', 'M Ashwin', 'NS Naik', 'PSP Handscomb',
       'J Yadav', 'UT Khawaja', 'F Behardien', 'BB Sran', 'S Kaushik',
       'ER Dwivedi'], dtype=object)

In [5]:
runs = deliveries.groupby("batsman")

In [6]:
runs.get_group("V Kohli")

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150410,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,5,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN

In [7]:
runs.get_group("V Kohli").shape

(3494, 21)

In [8]:
runs['batsman_runs'].sum().sort_values(ascending = False).head(10)

batsman
SK Raina          4548
V Kohli           4423
RG Sharma         4207
G Gambhir         4132
DA Warner         4014
RV Uthappa        3778
CH Gayle          3651
S Dhawan          3561
MS Dhoni          3560
AB de Villiers    3486
Name: batsman_runs, dtype: int64

In [9]:
runs['batsman_runs'].sum().sort_values(ascending = False).tail()

batsman
Abdur Razzak    0
S Kaushik       0
S Ladda         0
U Kaul          0
RR Bhatkal      0
Name: batsman_runs, dtype: int64

In [10]:
mask = deliveries['batsman_runs'] == 4

In [11]:
new_deliveries = deliveries[mask]

In [12]:
new_deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
30,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,5,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
32,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,1,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150403,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,11,4,V Kohli,AB de Villiers,BCJ Cutting,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150407,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,2,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150418,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,1,KL Rahul,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150447,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,6,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [13]:
new_deliveries.shape[0]

17033

In [14]:
mask = deliveries['batsman_runs'] == 6
new_deliveries = deliveries[mask]
new_deliveries
new_deliveries.shape[0]

6523

In [15]:
new_deliveries.groupby('batsman')['batsman_runs'].count().sort_values(ascending = False).head(10)

batsman
CH Gayle          266
SK Raina          174
RG Sharma         173
V Kohli           160
DA Warner         160
AB de Villiers    158
MS Dhoni          156
YK Pathan         149
KA Pollard        148
Yuvraj Singh      141
Name: batsman_runs, dtype: int64

In [16]:
mask = deliveries['batsman_runs'] == 3
new_deliveries = deliveries[mask]
new_deliveries
new_deliveries.shape[0]

509

In [17]:
new_deliveries.groupby('batsman')['batsman_runs'].count().sort_values(ascending = False).head(10)

batsman
M Vijay           17
S Dhawan          16
G Gambhir         15
AM Rahane         14
DA Warner         13
AB de Villiers    12
RV Uthappa        12
MEK Hussey        11
MS Dhoni          11
V Kohli           11
Name: batsman_runs, dtype: int64

In [18]:
vk = deliveries[deliveries['batsman'] == "V Kohli"]

In [19]:
vk.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending = False).head()

bowling_team
Chennai Super Kings    706
Delhi Daredevils       661
Kings XI Punjab        483
Mumbai Indians         447
Sunrisers Hyderabad    439
Name: batsman_runs, dtype: int64

In [20]:
def run_scores(batsman_name):
    vk = deliveries[deliveries['batsman'] == batsman_name]
    return vk.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending = False).index[0]

In [21]:
run_scores("V Kohli")

'Chennai Super Kings'

In [22]:
run_scores("DA Warner")

'Kolkata Knight Riders'

In [23]:
run_scores("G Gambhir")

'Kings XI Punjab'

In [24]:
run_scores("MS Dhoni")

'Royal Challengers Bangalore'

In [ ]:
# Strike Rate = (number of runs/ number of balls)*100
# min batsman 200 balls in over 16-20

In [27]:
death_over = deliveries[deliveries['over']>15]

In [31]:
all_batsman = death_over.groupby("batsman")['batsman_runs'].count()

In [41]:
x = all_batsman>200
batsman_list = all_batsman[x].index.tolist()

In [42]:
# runs scored by all these 43 batsman
#balls played by these 43 batsman

In [52]:
final = death_over[death_over["batsman"].isin(batsman_list)]

In [53]:
runs = final.groupby('batsman')['batsman_runs'].sum()

In [54]:
balls = final.groupby('batsman')['batsman_runs'].count()

In [55]:
sr = (runs/balls)*100

In [56]:
sr

batsman
A Mishra            100.888889
AB de Villiers      211.052632
AD Mathews          147.058824
AM Rahane           152.985075
AR Patel            142.794760
AT Rayudu           165.411765
BJ Hodge            157.402597
DA Miller           186.666667
DA Warner           189.473684
DJ Bravo            167.726161
DJ Hussey           175.213675
DPMD Jayawardene    152.032520
Harbhajan Singh     147.607656
IK Pathan           142.580645
JA Morkel           149.882353
JH Kallis           170.562771
JP Duminy           167.760618
JP Faulkner         149.319728
KA Pollard          161.336516
KD Karthik          152.051836
KM Jadhav           144.378698
LRPL Taylor         152.941176
MK Pandey           151.785714
MK Tiwary           140.189125
MS Dhoni            169.607843
NV Ojha             134.868421
P Kumar             109.701493
PP Chawla           120.257235
R Vinay Kumar       108.936170
RA Jadeja           130.729167
RG Sharma           175.668449
RV Uthappa          173.454545
S Badrinath         149.116608
S Dhawan            158.847737
SK Raina            167.467249
SPD Smith           169.303797
SS Tiwary           136.666667
STR Binny           144.036697
V Kohli             181.868132
WP Saha             163.389831
Y Venugopal Rao     148.846154
YK Pathan           159.246575
Yuvraj Singh        171.124031
Name: batsman_runs, dtype: float64